import {Montserrat} from 'next/font/google';
import "./globals.css";
import {SpeedInsights} from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react"

const mainFont = Montserrat({
    subsets: ['latin'],
    weight: ['300', '400', '500', '600', '700'],
    display: 'swap',
});

export const metadata = {
    weight: ['300', '400', '500', '700'],
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body>
        {children}
        <SpeedInsights/>
        <Analytics />
        </body>
        </html>
    );
}
